name: Cron for video friday mailing
on:
  schedule:
    - cron: "30 6 * * 5"
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call friday sheduler
        run: curl -X POST https://nfsw-telegram-bot.herokuapp.com/api/botFriday/sendFridayVideo
